<?php

namespace Proxies\__CG__\StickyBit\HospitalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Lit extends \StickyBit\HospitalBundle\Entity\Lit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setEtat($etat)
    {
        $this->__load();
        return parent::setEtat($etat);
    }

    public function getEtat()
    {
        $this->__load();
        return parent::getEtat();
    }

    public function getIdLit()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idLit"];
        }
        $this->__load();
        return parent::getIdLit();
    }

    public function setIdServ(\StickyBit\HospitalBundle\Entity\Service $idServ = NULL)
    {
        $this->__load();
        return parent::setIdServ($idServ);
    }

    public function getIdServ()
    {
        $this->__load();
        return parent::getIdServ();
    }

    public function setIdChambre(\StickyBit\HospitalBundle\Entity\Chambre $idChambre = NULL)
    {
        $this->__load();
        return parent::setIdChambre($idChambre);
    }

    public function getIdChambre()
    {
        $this->__load();
        return parent::getIdChambre();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'etat', 'idLit', 'idServ', 'idChambre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}