<?php

namespace Proxies\__CG__\StickyBit\HospitalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Facture extends \StickyBit\HospitalBundle\Entity\Facture implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setDateFacturation($dateFacturation)
    {
        $this->__load();
        return parent::setDateFacturation($dateFacturation);
    }

    public function getDateFacturation()
    {
        $this->__load();
        return parent::getDateFacturation();
    }

    public function setEtat($etat)
    {
        $this->__load();
        return parent::setEtat($etat);
    }

    public function getEtat()
    {
        $this->__load();
        return parent::getEtat();
    }

    public function setTotalFacture($totalFacture)
    {
        $this->__load();
        return parent::setTotalFacture($totalFacture);
    }

    public function getTotalFacture()
    {
        $this->__load();
        return parent::getTotalFacture();
    }

    public function getIdFacture()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idFacture"];
        }
        $this->__load();
        return parent::getIdFacture();
    }

    public function setIdDadmin(\StickyBit\HospitalBundle\Entity\DossierAdministratif $idDadmin = NULL)
    {
        $this->__load();
        return parent::setIdDadmin($idDadmin);
    }

    public function getIdDadmin()
    {
        $this->__load();
        return parent::getIdDadmin();
    }

    public function setIdPatient(\StickyBit\HospitalBundle\Entity\Patient $idPatient = NULL)
    {
        $this->__load();
        return parent::setIdPatient($idPatient);
    }

    public function getIdPatient()
    {
        $this->__load();
        return parent::getIdPatient();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'dateFacturation', 'etat', 'totalFacture', 'idFacture', 'idDadmin', 'idPatient');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}