parameters:
#    backend_medecin.example.class: Backend\MedecinBundle\Example

services:
#    backend_medecin.example:
#        class: %backend_medecin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
