parameters:
#    sticky_bit_hospital.example.class: StickyBit\HospitalBundle\Example

services:
#    sticky_bit_hospital.example:
#        class: %sticky_bit_hospital.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
