Dossier:
    type: entity
    table: dossier
    fields:
        idDossierpatient:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_dossierPatient
            generator:
                strategy: IDENTITY
        dateCreationDossier:
            type: datetime
            nullable: false
            column: date_creation_dossier
    manyToOne:
        idPatient:
            targetEntity: Patient
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_patient:
                    referencedColumnName: id_patient
            orphanRemoval: false
    lifecycleCallbacks: {  }
