LigneOrdonnace:
    type: entity
    table: ligne_ordonnace
    fields:
        idLigne:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_ligne
            generator:
                strategy: IDENTITY
        codeMed:
            type: integer
            unsigned: false
            nullable: false
            column: code_med
        nomMed:
            type: string
            length: 30
            fixed: false
            nullable: false
            column: nom_med
        description:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
