<?php

namespace Proxies\__CG__\StickyBit\HospitalBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Medicament extends \StickyBit\HospitalBundle\Entity\Medicament implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setLibMedic($libMedic)
    {
        $this->__load();
        return parent::setLibMedic($libMedic);
    }

    public function getLibMedic()
    {
        $this->__load();
        return parent::getLibMedic();
    }

    public function setQteValable($qteValable)
    {
        $this->__load();
        return parent::setQteValable($qteValable);
    }

    public function getQteValable()
    {
        $this->__load();
        return parent::getQteValable();
    }

    public function setEffectInd($effectInd)
    {
        $this->__load();
        return parent::setEffectInd($effectInd);
    }

    public function getEffectInd()
    {
        $this->__load();
        return parent::getEffectInd();
    }

    public function setPrix($prix)
    {
        $this->__load();
        return parent::setPrix($prix);
    }

    public function getPrix()
    {
        $this->__load();
        return parent::getPrix();
    }

    public function setQuantMin($quantMin)
    {
        $this->__load();
        return parent::setQuantMin($quantMin);
    }

    public function getQuantMin()
    {
        $this->__load();
        return parent::getQuantMin();
    }

    public function getIdMedicament()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idMedicament"];
        }
        $this->__load();
        return parent::getIdMedicament();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'libMedic', 'qteValable', 'effectInd', 'prix', 'quantMin', 'idMedicament');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}